name: Enable Auto Delete Head Branches

on:
  workflow_dispatch:

jobs:
  enable-auto-delete:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: 
          - "infotechay/Repo1"
          # Add more repositories as needed

    steps:
      - name: Enable Automatically Delete Head Branches
        id: enable-auto-delete
        run: |
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ matrix.repository }} \
            -d '{"delete_branch_on_merge": true}'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}