name: Update Cache Action Version

on:
  workflow_dispatch:
    inputs:
      repositories:
        description: "Comma-separated list of repositories (org/repo1,org/repo2,...)"
        required: true
        default: "org/repo1,org/repo2"
      branch_base:
        description: "Base branch to create feature branch from"
        required: true
        default: "development"
      feature_branch_prefix:
        description: "Prefix for the feature branch"
        required: true
        default: "update-cache-action"
      pat_token:
        description: "Personal Access Token (PAT) for GitHub authentication"
        required: true

jobs:
  update-cache:
    name: Update Cache Action Version
    runs-on: ubuntu-latest

    steps:
      # - name: Set up GitHub CLI
      #   env:
      #     GH_TOKEN: ${{ inputs.pat_token }}
      #   run: |
      #     echo $GH_TOKEN | gh auth login --with-token
      #     echo "GitHub CLI authenticated successfully."

      - name: Parse repository list
        id: parse_repos
        run: |
          echo "repositories=$(echo '${{ github.event.inputs.repositories }}' | tr ',' '\n')" >> $GITHUB_ENV

      - name: Process each repository
        env:
          GH_TOKEN: ${{ inputs.pat_token }}
        run: |
          for REPO in $repositories; do
            echo "Processing repository: $REPO"

            # Clone the repository
            if ! gh repo clone "$REPO" repo-dir; then
              echo "Failed to clone $REPO. Skipping..."
              continue
            fi

            cd repo-dir || { echo "Failed to navigate to repo-dir. Skipping..."; continue; }

            # Checkout the base branch
            BRANCH_BASE="${{ github.event.inputs.branch_base }}"
            if ! git checkout "$BRANCH_BASE"; then
              echo "Failed to checkout branch $BRANCH_BASE in $REPO. Skipping..."
              cd .. && rm -rf repo-dir
              continue
            fi

            # Create a new feature branch
            FEATURE_BRANCH="${{ github.event.inputs.feature_branch_prefix }}-$(date +%Y%m%d%H%M%S)"
            git checkout -b "$FEATURE_BRANCH"

            # Configure Git user
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"

            # Configure Git to use the PAT for authentication
            git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$REPO.git

            # Check and modify workflow files
            WORKFLOW_DIR=".github/workflows"
            CHANGED=false

            if [ -d "$WORKFLOW_DIR" ]; then
              for FILE in "$WORKFLOW_DIR"/*.yml; do
                if grep -q "actions/cache@v2" "$FILE"; then
                  echo "Found actions/cache@v2 in $FILE. Updating to actions/cache@v3..."
                  sed -i 's|actions/cache@v2|actions/cache@v3|g' "$FILE"
                  CHANGED=true
                fi
              done

              # Commit and push changes if any file was modified
              if [ "$CHANGED" = true ]; then
                git add "$WORKFLOW_DIR"
                git commit -m "Update actions/cache@v2 to actions/cache@v3"
                git push -u origin "$FEATURE_BRANCH"

                # Create a pull request
                gh pr create --title "Update actions/cache@v2 to actions/cache@v3" \
                  --body "This pull request updates GitHub Actions workflows to use actions/cache@v3, as actions/cache@v2 is deprecated." \
                  --base "$BRANCH_BASE" \
                  --head "$FEATURE_BRANCH"
                echo "Pull request created for $REPO."
              else
                echo "No changes detected in $REPO. Skipping commit and PR creation."
              fi
            else
              echo "No workflows directory found in $REPO. Skipping..."
            fi

            # Clean up
            cd ..
            rm -rf repo-dir
          done
